name: Testando Secret

on:
  push:
    branches:
      - main

jobs:
  testar-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Mostrar Secret
        run: echo "A chave é ${{ secrets.CHAVE_MESTRA }}"